# Generated by Django 4.1.7 on 2023-02-24 04:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sitio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lugar_sitio', models.CharField(choices=[('biblioteca', 'Biblioteca'), ('informatica 1', 'Informatica 1'), ('informatica 2', 'Informatica 2'), ('informatica 3', 'Informatica 3'), ('aula 1', 'Aula 1'), ('aula 2', 'Aula 2'), ('aula 3', 'Aula 3'), ('aula 4', 'Aula 4'), ('aula 5', 'Aula 5'), ('laboratorio 1', 'Laboratorio 1'), ('laboratorio 2', 'Laboratorio 2'), ('laboratorio 3', 'Laboratorio 3')], default=False, max_length=50)),
                ('tipo_usuario', models.CharField(choices=[('biblioteca', 'Biblioteca'), ('informatica ', 'Informatica '), ('aula ', 'Aula '), ('laboratorio ', 'Laboratorio ')], default=False, max_length=50)),
                ('aforo_maximo', models.PositiveIntegerField()),
                ('max_horas_diarias', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reserva', models.DateField(blank=True, null=True, verbose_name='Fecha de la reserva')),
                ('hora_inicio', models.TimeField(blank=True, null=True, verbose_name='Hora inicio')),
                ('hora_fin', models.TimeField(blank=True, null=True, verbose_name='Hora Fin')),
                ('estado_reserva', models.CharField(choices=[('realizada', 'Realizada'), ('por hacer', 'Por hacer')], default=False, max_length=20)),
                ('reservado', models.BooleanField(default=False)),
                ('sitio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='administrador.sitio', verbose_name='Sitio a reservar')),
                ('usuario', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
