# Generated by Django 4.1.7 on 2023-02-24 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='reservado',
            field=models.BooleanField(default=False, verbose_name='Asistió'),
        ),
    ]
